#!/bin/bash

# redirect all IO to a logfile
mkdir -p /usr/local/var/log
exec &>/usr/local/var/log/ntnuwifiautologin.log

# redirect all IO to /dev/null (comment this in if you don#t want to write to logfile)
#exec 1>/dev/null 2>/dev/null

# get a little breather before we get data for things to settle down
sleep 4

# get SSID
SSID=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I | awk '/ SSID:/ {print $2}'`
echo `date` "New SSID found: $SSID"

if [ "$SSID" != "ntnu_5g" ]; then
  exit 0
fi

username=
password=

echo `date` "Trying to get Firewall Login magic"

a=$(curl \
  --silent \
  --resolve wificert2.ntnu.edu.tw:140.122.131.1 \
  --connect-timeout 5 \
  --max-time 10 \
  --retry-all-errors \
  --retry 5 \
  --retry-delay 0 \
  --retry-max-time 40 \
  'https://wificert2.ntnu.edu.tw:1003/login?')
re='magic" value="([0-9a-zA-Z]+)"'

if [[ $a =~ $re ]]; then
  magic=${BASH_REMATCH[1]}
else
  exit 1
fi

echo `date` "Firewall Login magic: $magic"
echo `date` "Sending login request to wificert2.ntnu.edu.tw:1003"

curl \
  --resolve wificert2.ntnu.edu.tw:140.122.131.1 \
  --silent \
  --connect-timeout 5 \
  --max-time 10 \
  --retry-all-errors \
  --retry 5 \
  --retry-delay 0 \
  --retry-max-time 40 \
  'https://wificert2.ntnu.edu.tw:1003/' \
  -X 'POST' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Pragma: no-cache' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
  -H 'Accept-Language: en-us' \
  -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'Cache-Control: no-cache' \
  -H 'Host: wificert2.ntnu.edu.tw:1003' \
  -H 'Origin: https://wificert2.ntnu.edu.tw:1003' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15' \
  -H "Referer: https://wificert2.ntnu.edu.tw:1003/fgtauth?$magic" \
  --data "4Tredir=http%3A%2F%2Fcaptive.apple.com%2F&magic=$magic&username=$username&password=$password"

exit 0
